config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :attendees
  resources :users, only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendees, foreign_key: "attended_event_id"
  has_many :users, through: :attendees, source: :attendee

  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendees, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendees, source: :attended_event

  def attending?(event)
    event.users.include?(self)
  end

  def attend!(event)
    self.attendees.create!(attended_event_id: event.id)
  end

  def cancel!(event)
    self.attendees.find_by(attended_event_id: event.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
    @event = Attendee.find(params[:attendee][:attended_event_id])
    current_user.attend!(@event)
    redirect_to @event
  end

  def destroy
    @event = Attendee.find(params[:id]).attended_event
    current_user.cancel!(@event)
    redirect_to @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = current_user.created_events.build
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.users
  end

  def create
    @event = current_user.created_events.new(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @created_events = @user.created_events
    @attended_events = @user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend.html.erb
<% if user_signed_in? %>
  <%= form_for current_user.attendees.build(attended_event: @event) do |form| %>
    <%= form.hidden_field :attended_event_id %>
    <%= form.submit "Attend" %>
  <% end %>
<% end %>

app/views/events/_attend_cancel.html.erb
<% if user_signed_in? && current_user.attending?(@event) %>
  <%= render "cancel" %>
<% else %>
  <%= render "attend" %>
<% end %>

app/views/events/_cancel.html.erb
<%= form_for current_user.attendees.find_by(attended_event_id: @event.id), html: { method: :delete } do |form|  %>
  <%= form.submit "Cancel" %>
<% end %>

app/views/events/_event.html.erb
<li>
  <div>
    <h4><%= link_to event.name, event_path(event) %></h4>
    <p>
      Location:
      <%= event.location %>
      Date:
      <%= event.date %>
    </p>
  </div>
</li>

app/views/events/index.html.erb
<h1>Welcome to Private Events!</h1>

<h2>Upcoming events</h2>
<% if @events.upcoming.any? %>
  <ul>
    <%= render @events.upcoming %>
  </ul>
<% else %>  
  <%= link_to "Add Event", new_event_path %>
<% end %>

<h2>Past events</h2>
<% if @events.past.any? %>
  <ul>
    <%= render @events.past %>
  </ul>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/events/show.html.erb
<div>
  <h1><%= @event.name %></h1>
  <div>
    <%= render "attend_cancel" %>
  </div>

  <p>Location: <%= @event.location %></p>
  <p>Date: <%= @event.date %></p>
  
  <% if @event.users.any? %>
    <% @event.users.each do |user| %>
      <span><%= user.email %></span>
    <% end %>
  <% else %>
    No attendees
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.email %>!</h1>

<%= link_to "Create an Event", new_event_path %>

<h2>Created events</h2>
<ul>
  <% @created_events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %>
    </li>
  <% end %>
</ul>

<h2>Attended events</h2>
<ul>
  <% @attended_events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %>
    </li>
  <% end %>
</ul>